import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactQuaryClientProvider } from "../app/Providers/ReactQuaryClientProvider";
import { Toaster } from "react-hot-toast";
import { GoogleOAuthProvider } from "@react-oauth/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const CLIENT_ID:any= process.env.NEXT_PUBLIC_CLIENT_ID;
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQuaryClientProvider>
        <GoogleOAuthProvider clientId={CLIENT_ID}>
          <div>{children} </div>
          <Toaster position="top-right" reverseOrder={false} />
          </GoogleOAuthProvider>
        </ReactQuaryClientProvider>
      </body>
    </html>
  );
}
